micronaut:
  cashes:
    headlines:
      charset: 'UTF-8'
  application:
    name: demo
  server:
    cors:
      enabled: true
      configurations:
        default:
          allowed-origins:
            - "*"
          allowed-methods :
            -POST
            -GET
            -PUT
            -DELETE
            -OPTIONS
          allowed-headers:

            - "*"

          exposedHeaders:
            -Authorization
          allowCredentials: true

  security:
    enabled: true
    authentication: bearer
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: this-is-a-very-strong-secret-key-12345678

jpa:
  default:
    packages-to-scan:
      - com.example
    entity-scan:
      packages:
        - com.example
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true

datasources:
  default:
    url: jdbc:mysql://localhost:3306/loyalty?rewriteBatchedStatements=true&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&useCompression=true&autoReconnect=true&serverTimezone=Europe/Rome&allowPublicKeyRetrieval=true
    db-type: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ""  # Replace with real password if needed
    minimumIdle: 0
    maximumPoolSize: 5
    connectionTimeout: 50000
    maxLifetime: 300000
    idleTimeout: 30000
    validationTimeout: 50000
    transaction-aware: true




